package com.pherrera.rest.entity;
// Generated 20-jun-2018 8:46:29 by Hibernate Tools 3.5.0.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Lineas generated by hbm2java
 */
@Entity
@Table(name = "lineas", catalog = "tiendadb")
public class Lineas implements java.io.Serializable {

	private int id;
	private String linea;
	private String icono;

	public Lineas() {
	}

	public Lineas(int id, String linea, String icono) {
		this.id = id;
		this.linea = linea;
		this.icono = icono;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "linea", nullable = false, length = 100)
	public String getLinea() {
		return this.linea;
	}

	public void setLinea(String linea) {
		this.linea = linea;
	}

	@Column(name = "icono", nullable = false, length = 20)
	public String getIcono() {
		return this.icono;
	}

	public void setIcono(String icono) {
		this.icono = icono;
	}

}
