package com.pherrera.rest.entity;
// Generated 20-jun-2018 8:46:29 by Hibernate Tools 3.5.0.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * OrdenesDetalle generated by hbm2java
 */
@Entity
@Table(name = "ordenes_detalle", catalog = "tiendadb")
public class OrdenesDetalle implements java.io.Serializable {

	private Integer id;
	private int ordenId;
	private String productoId;

	public OrdenesDetalle() {
	}

	public OrdenesDetalle(int ordenId, String productoId) {
		this.ordenId = ordenId;
		this.productoId = productoId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "orden_id", nullable = false)
	public int getOrdenId() {
		return this.ordenId;
	}

	public void setOrdenId(int ordenId) {
		this.ordenId = ordenId;
	}

	@Column(name = "producto_id", nullable = false, length = 15)
	public String getProductoId() {
		return this.productoId;
	}

	public void setProductoId(String productoId) {
		this.productoId = productoId;
	}

}
