package com.pherrera.rest.entity;
// Generated 20-jun-2018 8:46:29 by Hibernate Tools 3.5.0.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Ordenes generated by hbm2java
 */
@Entity
@Table(name = "ordenes", catalog = "tiendadb")
public class Ordenes implements java.io.Serializable {

	private Integer id;
	private int usuarioId;
	private Date creadoEn;

	public Ordenes() {
	}

	public Ordenes(int usuarioId, Date creadoEn) {
		this.usuarioId = usuarioId;
		this.creadoEn = creadoEn;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "usuario_id", nullable = false)
	public int getUsuarioId() {
		return this.usuarioId;
	}

	public void setUsuarioId(int usuarioId) {
		this.usuarioId = usuarioId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "creado_en", nullable = false, length = 19)
	public Date getCreadoEn() {
		return this.creadoEn;
	}

	public void setCreadoEn(Date creadoEn) {
		this.creadoEn = creadoEn;
	}

}
